# Generated by Django 3.2.11 on 2023-03-19 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='地名')),
                ('address', models.CharField(max_length=64, null=True, verbose_name='地名')),
            ],
            options={
                'db_table': 'shop_place',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='餐厅名')),
                ('place', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.place', verbose_name='所在位置')),
            ],
            options={
                'db_table': 'shop_restaurant',
            },
        ),
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='服务员名字')),
                ('induction', models.DateTimeField(null=True, verbose_name='入职时间')),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.restaurant', verbose_name='所属餐厅')),
            ],
            options={
                'db_table': 'shop_waiter',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='食物名字')),
                ('is_main', models.BooleanField(default=False, null=True, verbose_name='是否是主食')),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.restaurant', verbose_name='所属餐厅')),
            ],
            options={
                'db_table': 'shop_food',
            },
        ),
    ]
