# Generated by Django 3.2.11 on 2023-03-18 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_auto_20230318_0825'),
    ]

    operations = [
        migrations.CreateModel(
            name='PLace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 't_place',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('palace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user_app.place')),
                ('servers_hot', models.BooleanField(default=False)),
                ('servers_cool', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 't_restaurant',
            },
        ),
    ]
