# Generated by Django 3.2.11 on 2023-03-19 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_auto_20230318_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.area')),
            ],
        ),
    ]
